apiVersion: 1

datasources:
  - name: MySQL
    type: mysql
    url: dbcloud:3306
    database: AirLuxDB
    user: grafana
    jsonData:
      maxOpenConns: 0 # Grafana v5.4+
      maxIdleConns: 2 # Grafana v5.4+
      connMaxLifetime: 14400 # Grafana v5.4+
    secureJsonData:
      password: ${GRAFANA_MYSQL_PASSWORD}