apiVersion: apps/v1
kind: Deployment
metadata:
  name: airlux-api
  annotations:
    keel.sh/policy: force
    keel.sh/trigger: poll      
    keel.sh/pollSchedule: "@every 1m"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airlux-api
  template:
    metadata:
      labels:
        app: airlux-api
    spec:
      containers:
      - image: supersieu/airlux-api
        name: airlux-api
        ports:
        - containerPort: 80