CREATE SCHEMA IF NOT EXISTS AirLuxDB character set utf8mb4 collate utf8mb4_bin; 
CREATE TABLE IF NOT EXISTS  AirLuxDB.users (
    id VARCHAR(255) NOT NULL, 
    email VARCHAR(255) NOT NULL, 
    password VARCHAR(255) NOT NULL, 
    name VARCHAR(255) NOT NULL, 
    device_id VARCHAR(255), 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    UNIQUE INDEX id_UNIQUE (id ASC))CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS AirLuxDB.user_building (
    id int  AUTO_INCREMENT, 
    building_id VARCHAR(255) NOT NULL, 
    user_id VARCHAR(255) NOT NULL, 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    UNIQUE INDEX id_UNIQUE (id ASC))CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS AirLuxDB.buildings (
    id VARCHAR(255) NOT NULL, 
    name VARCHAR(255) NOT NULL, 
    type VARCHAR(255), 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    UNIQUE INDEX id_UNIQUE (id ASC))CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS AirLuxDB.rooms (
    id VARCHAR(255) NOT NULL, 
    building_id VARCHAR(255) NOT NULL, 
    name VARCHAR(255) NOT NULL, 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    UNIQUE INDEX id_UNIQUE (id ASC))CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS AirLuxDB.captors (
    id VARCHAR(255) NOT NULL, 
    name VARCHAR(255) NOT NULL, 
    room_id VARCHAR(255) NOT NULL, 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    UNIQUE INDEX id_UNIQUE (id ASC))CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS AirLuxDB.captor_values (
    id INT AUTO_INCREMENT,
    captor_id VARCHAR(255) NOT NULL,
    value INT NOT NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    UNIQUE INDEX id_UNIQUE (id ASC))CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
CREATE TABLE IF NOT EXISTS AirLuxDB.devices (
    id VARCHAR(255) NOT NULL, 
    apns_token VARCHAR(255) NOT NULL, 
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP, 
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    UNIQUE INDEX id_UNIQUE (id ASC))CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;

CREATE USER 'root'@'syncapi.docker_iotnetwork' IDENTIFIED BY 'password'; 
GRANT ALL PRIVILEGES ON *.* TO 'root'@'syncapi.docker_iotnetwork' WITH GRANT OPTION; 